### ISSUE TITLE
Install plugin

### ISSUE THREAD

**Issue by alemoles** [eea/eea.elasticsearch.river.rdf#15]
Development team, when I try to install the plugin in ES 2.3.0, ES didn't install the plugin because is mandatory have 'plugin-descriptor.properties', how i can fix this problem. Thanks in advance

**Comment by demarant** [comment]
@alemoles

We don't support elasticsearch 2.x

Elastisearch har removed support for river plugins from 2.0 release.
https://www.elastic.co/guide/en/elasticsearch/rivers/current/index.html

We plan to create a distinct package (docker image) which will have similar functionality as the rdf river plugin.
