### ISSUE TITLE
Which versions of ElasticSearch are supported?

### ISSUE THREAD

**Issue by paulrigor** [eea/eea.elasticsearch.river.rdf#17]
Hello, 

Just came across your neat project. Was wondering whether there are specific versions of ES that this tool currently supports?

Thanks!

**Comment by zschoenb** [comment]
Also very interested in support for newer versions of ES. This is an incredibly useful tool.

**Comment by zotya** [comment]
Hi,

We only use the river in ES version 1.3 and 1.7.x.
According to: 
https://www.elastic.co/blog/deprecating-rivers
https://www.elastic.co/guide/en/elasticsearch/plugins/5.x/integrations.html
Elasticsearch releases 2.0 and later do not support rivers.
