### ISSUE TITLE
Bulk Loading of large RDF file and matching by triple pattern

### ISSUE THREAD

**Issue by laurensdv** [eea/eea.elasticsearch.river.rdf#7]
1. Suppose I have a large datadump in Turtle or Ntriples on my localdisk, how can I load into the store? Do I need to publish it on a local webserver, and use the uri of the file to index it?

2. Once I have loaded the entire file containing triples, can I use a filter operation to match 
?s ?p ?o where I bind any of those ?s ?p ?o to a resource or a literal? or does it only support 'match' -> does it mean that the matching occurs by string?

3. If I have a SPARQL query that wasn't indexed before can I send it to the indexed version of the data resource of my file? Or is SPARQL not supported as such and are just the results of a SPARQL query indexed, so if it's a first time request it would need to be sent to the original endpoint and then the second time it.

**Comment by demarant** [comment]
he original question has been answered by iulia.
@hemed a new version of the [rdf river for ES 1.4.2](https://github.com/eea/eea.elasticsearch.river.rdf/releases) is now also available and we also have better [error handling](http://taskman.eionet.europa.eu/issues/20968) @pblin 
so closing this question.

**Comment by demarant** [comment]
regarding the question about uploading large RDF files/large SPARQL queries which may end up in timeout, you can split your RDF in multiple files or optimise your queries. More tips are found on [this wiki page](http://taskman.eionet.europa.eu/projects/zope/wiki/HowToWriteOptimalSPARQLQueries)
